[package]
name = "ini-roundtrip"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/VorpalBlade/ini-roundtrip"

authors = ["Arvid Norlander"]
description = "Fast format preserving (round-tripping) INI-parser"
keywords = ["ini", "no-std", "config", "configuration", "parser"]
categories = ["config", "parser-implementations"]

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "basic_bench"
harness = false

[dependencies]
cfg-if = "1.0.0"
